"use client";
import Head from "next/head"
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub, AiFillAccountBook} from 'react-icons/ai'
import Image from "next/image"
import profilePic from '../public/images/profilePic.jpg'
import p2_1 from '../public/images/p2_1.png'
import p3_1 from '../public/images/p3_1.png'
import p4_1 from '../public/images/p4_1.png'
// import p2_1 from '../public/images/p2_1.png'
import { useState } from "react"


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Michael Clark Portfolio</title>
        <meta name='description' content='Generated by create react app'/>
        <link rel='icon' href='/favicon.ico' />
      </Head>
       <main className="  bg-white px-10 md:px-20 lg:px40 dark:bg-slate-600" >
        <section className=" min-h-screen"> 
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className="text-xl" >My Projects</h1>
            <ul className=" flex items-center">
              <li></li>
              <li> <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-2xl" /> </li>
              <li><a className=" bg-gradient-to-r from-cyan-400 to-teal-400 text-white px-4 py-2 rounded ml-4" href="https://www.linkedin.com/in/mikec7592/">Linkedin</a></li>
              <li> <a className=" bg-gradient-to-r from-cyan-400 to-teal-400 text-white px-4 py-2 rounded ml-4"  href="#">Resume</a></li>
            </ul>
          </nav>
          <div className=" p-10 text-center" >
            <h2 className=" py-2 text-5xl text-teal-600 font-medium md:text-6xl" >Michael Clark</h2>
            <h3 className=" text-2xl py-2 md:text-3xl" >Full-Stack Engineer</h3>
            <p className=" text-md py-2 leading-8 text-gray-700 md:text-xl max-w-xl mx-auto" >Aspiring engineer with a dream to one day help guide and mentor other budding engineers!  </p>
          </div>
          <div className=" text-5xl flex justify-center py-3 text-emerald-600"> 
            <a className=" mx-10"> <AiFillLinkedin/> </a>
            <a className=" mx-10"> <AiFillGithub/> </a>
          </div>
          <div className=" relative rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96" >
            <Image src={profilePic} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1" >Skills & Training</h3>
            <p className=" text-md py-2 leading-8 text-gray-700" >Completed <span className=" text-teal-600" >General Assemblys</span> software engineering bootcamp where I recieved extensive training in Full-Stack development with a certificate for my accomplishments.  I also recieved extensive Front-end industry training from my time at <span className=" text-teal-600" >Brainnest Consulting</span> and recieved a certifcate of my accomplishments upon my departure from them.</p>
            <p className=" text-md py-2 leading-8 text-gray-700" >Check out some of my projects below</p>
          </div>
          <div className=" lg:flex gap-10" > 
            <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-600"  >
              <Image className=" mx-auto" src={p2_1} width={100} height={100} />
              <h3>AnimeList</h3>
              <p>
                A web app where a user can create an account and keep track of their anime collection, add animes to a watch list and rate individual animes. 
              </p>
              <h4 className=" py-4 text-teal-600">Some technologies used:</h4>
              <p className="py-1 text-gray-700">NodeJS</p>
              <p className="py-1 text-gray-700">Javascript</p>
              <p className="py-1 text-gray-700">Express/MongoDB</p>
              <p className="py-1 text-gray-700">BCrypt/salt+hash</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10" >
              <Image className=" mx-auto" src={p3_1} width={100} height={100} />
              <h3>AnimeList</h3>
              <p>
                A web app where a user can create an account and keep track of their anime collection, add animes to a watch list and rate individual animes. 
              </p>
              <h4 className=" py-4 text-teal-600">Some technologies used:</h4>
              <p className="py-1 text-gray-700">NodeJS</p>
              <p className="py-1 text-gray-700">Javascript</p>
              <p className="py-1 text-gray-700">Express/MongoDB</p>
              <p className="py-1 text-gray-700">BCrypt/salt+hash</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10" >
              <Image className=" mx-auto" src={p4_1} width={100} height={100} />
              <h3>AnimeList</h3>
              <p>
                A web app where a user can create an account and keep track of their anime collection, add animes to a watch list and rate individual animes. 
              </p>
              <h4 className=" py-4 text-teal-600">Some technologies used:</h4>
              <p className="py-1 text-gray-700">NodeJS</p>
              <p className="py-1 text-gray-700">Javascript</p>
              <p className="py-1 text-gray-700">Express/MongoDB</p>
              <p className="py-1 text-gray-700">BCrypt/salt+hash</p>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10" >
              <Image className=" mx-auto" src={p2_1} width={100} height={100} />
              <h3>AnimeList</h3>
              <p>
                A web app where a user can create an account and keep track of their anime collection, add animes to a watch list and rate individual animes. 
              </p>
              <h4 className=" py-4 text-teal-600">Some technologies used:</h4>
              <p className="py-1 text-gray-700">NodeJS</p>
              <p className="py-1 text-gray-700">Javascript</p>
              <p className="py-1 text-gray-700">Express/MongoDB</p>
              <p className="py-1 text-gray-700">BCrypt/salt+hash</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className=" text-md py-2 leading-8 text-gray-700" >Completed <span className=" text-teal-600" >General Assemblys</span> software engineering bootcamp where I recieved extensive training in Full-Stack development with a certificate for my accomplishments.  I also recieved extensive Front-end industry training from my time at <span className=" text-teal-600" >Brainnest Consulting</span> and recieved a certifcate of my accomplishments upon my departure from them.</p>
            <p className=" text-md py-2 leading-8 text-gray-700" >Check out some of my projects below</p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={p2_1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={p3_1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={p4_1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={p2_1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}